### PR TITLE
Update CM-Guides “guardian/power-firebrand/static”

### PR DESCRIPTION
**Pull request by typing-noise**
Automatically generated by Netlify CMS

reorganized the qfb page putting all the guides into sections with titles so its easier to see which is which.

wrote up rotations for double guard and double soulbeast comps on MAMA

### CODE REVIEW

**Comment by typing-noise** [comment]
Added a role specific preamble in the overview section

**Comment by gw2princeps** [comment]
Did you edit this file in an external editor somehow? There are a lot of carriage returns and escapes that are not supposed to be there

**Comment by typing-noise** [comment]
yes, i did it so its easier to keep track of the hierarchy. It didnt look like it impacted anything, but should i not?

**Comment by gw2princeps** [comment]
It should be fine, but I am a little bit cautious. The system is not entirely stable unfortunately. 

So for once you will need to adjust the indentation. Since we are using mdx/v1 indented components will not get parsed correctly. For the cms we are already on mdx/v2 which can parse these correctly. Therefore the cms might show something just fine but it will be broken on the live site. 

If you check other files you will see that before and after every component there is a an enter

**Pull request merged**
